name: .NET Core CI

on: [push]

env:
  AZURE_WEBAPP_NAME: typescript-doc-demo    # set this to your application's name
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

defaults:
  run:
    shell: bash
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install dependencies
        run: bundle install
      - name: Jekyll build
        run: jekyll build

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: 'docs/_site'